import { useEffect, useMemo, useRef, useState } from 'react'
import ProgressView from './ProgressView'
import WeekView from './WeekView'
import FoodImportView from './FoodImportView'
import CaptureFoodSheet from './CaptureFoodSheet'

type NutritionField = 'calories' | 'protein' | 'carbohydrates' | 'fat' | 'sugar'
type MealPeriod = 'breakfast' | 'morning_snack' | 'lunch' | 'afternoon_snack' | 'dinner' | 'evening_snack' | 'snack' | 'drink'

type Profile = { id: string; display_name: string; daily_calorie_target: number; weekly_exercise_minutes_target: number; hydration_target_ml?: number | null; exercise_credit_mode: 'none' | 'full' | 'percentage'; exercise_credit_percentage: number; nutrition_display_mode: 'simple' | 'balanced' | 'detailed'; nutrition_display_fields: NutritionField[]; timezone: string; measurement_units: 'metric'; archived: boolean }
type DiaryEntry = { id: string; food_id?: string | null; food_name: string; serving_name: string; meal_period: MealPeriod; servings: number; calories: number; protein_g?: number | null; carbohydrates_g?: number | null; fat_g?: number | null; sugar_g?: number | null; consumed_at: string; source?: string }
type PlannedEntry = { id: string; food_id?: string | null; food_name: string; serving_name: string; meal_period: MealPeriod; servings: number; calories: number; protein_g?: number | null; carbohydrates_g?: number | null; fat_g?: number | null; sugar_g?: number | null; planned_for: string; status: 'planned' | 'consumed' | 'skipped'; source?: string }
type DayPlan = { profile_id: string; date: string; calorie_target: number; consumed_calories: number; planned_calories: number; remaining_after_planned: number; protein_g: number; carbohydrates_g: number; fat_g: number; sugar_g: number; planned: PlannedEntry[]; consumed: DiaryEntry[] }
type SearchResult = { id: string; source: 'healthhub' | 'foodhub'; result_type: string; name: string; subtitle?: string | null; calories?: number | null; nutrition_complete: boolean }
type FoodDraft = { name: string; brand: string; serving_name: string; serving_grams: string; calories: string; energy_kj: string; protein_g: string; carbohydrates_g: string; fat_g: string; sugar_g: string }
type ProfileDraft = { display_name: string; daily_calorie_target: string; weekly_exercise_minutes_target: string; hydration_target_ml: string; exercise_credit_mode: 'none' | 'full' | 'percentage'; exercise_credit_percentage: string; nutrition_display_fields: NutritionField[] }

const API = './api/v1'
const mealSections: { value: MealPeriod; label: string }[] = [
  { value: 'breakfast', label: 'Breakfast' }, { value: 'morning_snack', label: 'Morning Snack' }, { value: 'lunch', label: 'Lunch' }, { value: 'afternoon_snack', label: 'Afternoon Snack' }, { value: 'dinner', label: 'Dinner' }, { value: 'evening_snack', label: 'Evening Snack' }, { value: 'drink', label: 'Drinks' },
]
const nutritionChoices: { value: NutritionField; label: string }[] = [
  { value: 'calories', label: 'Calories' }, { value: 'protein', label: 'Protein' }, { value: 'carbohydrates', label: 'Carbohydrates' }, { value: 'fat', label: 'Fat' }, { value: 'sugar', label: 'Sugar' },
]
const emptyFood: FoodDraft = { name: '', brand: '', serving_name: '1 serve', serving_grams: '', calories: '', energy_kj: '', protein_g: '', carbohydrates_g: '', fat_g: '', sugar_g: '' }
const emptyProfile: ProfileDraft = { display_name: '', daily_calorie_target: '2000', weekly_exercise_minutes_target: '150', hydration_target_ml: '', exercise_credit_mode: 'none', exercise_credit_percentage: '0', nutrition_display_fields: ['calories', 'protein'] }

function todayIso() { return new Intl.DateTimeFormat('en-CA').format(new Date()) }
function addDays(day: string, offset: number) { const value = new Date(`${day}T12:00:00`); value.setDate(value.getDate() + offset); return new Intl.DateTimeFormat('en-CA').format(value) }
function displayDay(day: string) { return new Intl.DateTimeFormat('en-AU', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(`${day}T12:00:00`)) }
function legacyMode(fields: NutritionField[]): Profile['nutrition_display_mode'] { if (fields.length === 1 && fields[0] === 'calories') return 'simple'; if (fields.length === 2 && fields.includes('calories') && fields.includes('protein')) return 'balanced'; if (['calories', 'protein', 'carbohydrates', 'fat'].every((field) => fields.includes(field as NutritionField))) return 'detailed'; return 'simple' }
function normaliseMeal(value: MealPeriod): MealPeriod { return value === 'snack' ? 'afternoon_snack' : value }

function NutritionMultiSelect({ value, onChange }: { value: NutritionField[]; onChange: (value: NutritionField[]) => void }) {
  function toggle(field: NutritionField) { if (value.includes(field)) { if (value.length === 1) return; onChange(value.filter((item) => item !== field)) } else onChange([...value, field]) }
  const label = nutritionChoices.filter((choice) => value.includes(choice.value)).map((choice) => choice.label).join(', ')
  return <details className="multi-select"><summary>{label || 'Select nutrition'}</summary><div className="multi-select-menu">{nutritionChoices.map((choice) => <label key={choice.value}><input type="checkbox" checked={value.includes(choice.value)} onChange={() => toggle(choice.value)} />{choice.label}</label>)}</div></details>
}

export default function App() {
  const [profiles, setProfiles] = useState<Profile[]>([])
  const [activeProfileId, setActiveProfileId] = useState<string | null>(null)
  const [view, setView] = useState<'today' | 'week' | 'progress' | 'settings' | 'food-import'>('today')
  const [selectedDay, setSelectedDay] = useState(todayIso())
  const [dayPlan, setDayPlan] = useState<DayPlan | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)
  const [quickAddOpen, setQuickAddOpen] = useState(false)
  const [captureOpen, setCaptureOpen] = useState(false)
  const [search, setSearch] = useState('')
  const [searchResults, setSearchResults] = useState<SearchResult[]>([])
  const [searching, setSearching] = useState(false)
  const [mealPeriod, setMealPeriod] = useState<MealPeriod>('afternoon_snack')
  const [quickAddMode, setQuickAddMode] = useState<'eaten' | 'planned'>('eaten')
  const [quickServings, setQuickServings] = useState('1')
  const [savingEntry, setSavingEntry] = useState(false)
  const [foodDraft, setFoodDraft] = useState<FoodDraft>(emptyFood)
  const [savingFood, setSavingFood] = useState(false)
  const [profileDraft, setProfileDraft] = useState<ProfileDraft>(emptyProfile)
  const [savingProfile, setSavingProfile] = useState(false)
  const searchAbort = useRef<AbortController | null>(null)

  const activeProfile = useMemo(() => profiles.find((profile) => profile.id === activeProfileId) ?? null, [profiles, activeProfileId])
  const displayFields = activeProfile?.nutrition_display_fields ?? ['calories']

  async function loadDay(profileId: string, day = selectedDay) { const response = await fetch(`${API}/profiles/${profileId}/day-plan?day=${day}`); if (!response.ok) throw new Error('Could not load the daily diary'); setDayPlan((await response.json()) as DayPlan) }

  useEffect(() => { async function load() { try { const [profilesResponse, activeResponse] = await Promise.all([fetch(`${API}/profiles`), fetch(`${API}/active-profile`)]); if (!profilesResponse.ok) throw new Error('Could not load profiles'); const profileData = (await profilesResponse.json()) as Profile[]; setProfiles(profileData); let selected: string | null = null; if (activeResponse.ok) { const active = await activeResponse.json(); if (active?.profile_id) selected = active.profile_id } if (!selected && profileData.length === 1) selected = profileData[0].id; setActiveProfileId(selected); if (selected) await loadDay(selected, todayIso()) } catch (err) { setError(err instanceof Error ? err.message : 'HealthHub could not be loaded') } finally { setLoading(false) } } void load() }, [])
  useEffect(() => { if (activeProfileId && view === 'today') void loadDay(activeProfileId, selectedDay).catch((err) => setNotice(err instanceof Error ? err.message : 'Could not load day')) }, [activeProfileId, selectedDay, view])

  useEffect(() => {
    if (!quickAddOpen || !activeProfileId) return
    if (search.trim().length < 2) {
      searchAbort.current?.abort(); setSearching(false)
      void fetch(`${API}/quick-add/local-search?profile_id=${activeProfileId}&limit=12`).then(async (response) => { if (response.ok) setSearchResults((await response.json()) as SearchResult[]) })
      return
    }
    const timer = window.setTimeout(async () => {
      searchAbort.current?.abort(); const controller = new AbortController(); searchAbort.current = controller; const query = encodeURIComponent(search.trim())
      try {
        setSearching(true)
        const localResponse = await fetch(`${API}/quick-add/local-search?q=${query}&profile_id=${activeProfileId}`, { signal: controller.signal }); if (!localResponse.ok) throw new Error('Search failed'); setSearchResults((await localResponse.json()) as SearchResult[])
        const foodHubResponse = await fetch(`${API}/quick-add/foodhub-search?q=${query}`, { signal: controller.signal }); if (foodHubResponse.ok) { const extra = (await foodHubResponse.json()) as SearchResult[]; setSearchResults((current) => { const keys = new Set(current.map((item) => `${item.source}:${item.id}`)); return [...current, ...extra.filter((item) => !keys.has(`${item.source}:${item.id}`))].slice(0, 12) }) }
      } catch (err) { if (!(err instanceof DOMException && err.name === 'AbortError')) setNotice(err instanceof Error ? err.message : 'Search failed') }
      finally { if (searchAbort.current === controller) setSearching(false) }
    }, 250)
    return () => window.clearTimeout(timer)
  }, [search, quickAddOpen, activeProfileId])

  async function switchProfile(profileId: string) { setActiveProfileId(profileId); try { const response = await fetch(`${API}/active-profile`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile_id: profileId }) }); if (!response.ok) throw new Error('Could not switch profile'); await loadDay(profileId, selectedDay); setNotice('Profile switched') } catch (err) { setError(err instanceof Error ? err.message : 'Could not switch profile') } }
  async function addSearchResult(result: SearchResult) { if (!activeProfileId || savingEntry) return; const numericServings = Number(quickServings); if (!Number.isFinite(numericServings) || numericServings <= 0) { setNotice('Servings must be greater than zero'); return } setSavingEntry(true); try { if (result.source === 'foodhub' && quickAddMode === 'planned') { const plannedFor = new Date(`${selectedDay}T12:00:00`).toISOString(); const response = await fetch(`${API}/profiles/${activeProfileId}/planned/foodhub/${result.id}?meal_period=${mealPeriod}&planned_for=${encodeURIComponent(plannedFor)}&servings=${numericServings}`, { method: 'POST' }); if (!response.ok) { setNotice('FoodHub recipe nutrition is unavailable'); return } } else if (result.source === 'foodhub') { const response = await fetch(`${API}/profiles/${activeProfileId}/diary/foodhub/${result.id}?meal_period=${mealPeriod}&servings=${numericServings}`, { method: 'POST' }); if (!response.ok) { setNotice('FoodHub recipe nutrition is unavailable'); return } } else if (quickAddMode === 'planned') { const plannedFor = new Date(`${selectedDay}T12:00:00`).toISOString(); const response = await fetch(`${API}/profiles/${activeProfileId}/planned`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ food_id: result.id, meal_period: mealPeriod, planned_for: plannedFor, servings: numericServings }) }); if (!response.ok) { setNotice('Could not add this item to the plan'); return } } else { const consumedAt = new Date(`${selectedDay}T12:00:00`).toISOString(); const response = await fetch(`${API}/profiles/${activeProfileId}/diary`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ food_id: result.id, meal_period: mealPeriod, consumed_at: consumedAt, servings: numericServings }) }); if (!response.ok) { setNotice('Could not add this item to the diary'); return } } await loadDay(activeProfileId, selectedDay); setQuickAddOpen(false); setSearch(''); setQuickServings('1'); setNotice(`${result.name} added`) } finally { setSavingEntry(false) } }
  async function consumePlanned(entry: PlannedEntry) { if (!activeProfileId) return; const response = await fetch(`${API}/profiles/${activeProfileId}/planned/${entry.id}/consume`, { method: 'POST' }); if (response.ok) { await loadDay(activeProfileId, selectedDay); setNotice('Planned item marked eaten') } }
  async function deletePlanned(entry: PlannedEntry) { if (!activeProfileId) return; const response = await fetch(`${API}/profiles/${activeProfileId}/planned/${entry.id}`, { method: 'DELETE' }); if (response.ok) { await loadDay(activeProfileId, selectedDay); setNotice('Planned item removed') } }
  async function deleteDiary(entry: DiaryEntry) { if (!activeProfileId) return; const response = await fetch(`${API}/profiles/${activeProfileId}/diary/${entry.id}`, { method: 'DELETE' }); if (response.ok) { await loadDay(activeProfileId, selectedDay); setNotice('Diary entry removed') } }
  async function editPlanned(entry: PlannedEntry) { if (!activeProfileId) return; const servings = window.prompt('Servings', String(entry.servings)); if (servings == null) return; const meal = window.prompt('Meal section', normaliseMeal(entry.meal_period)); if (meal == null) return; const response = await fetch(`${API}/profiles/${activeProfileId}/planned/${entry.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ servings: Number(servings), meal_period: meal }) }); if (response.ok) await loadDay(activeProfileId, selectedDay); else setNotice('Could not update planned item') }
  async function editDiary(entry: DiaryEntry) { if (!activeProfileId) return; const servings = window.prompt('Servings', String(entry.servings)); if (servings == null) return; const meal = window.prompt('Meal section', normaliseMeal(entry.meal_period)); if (meal == null) return; const response = await fetch(`${API}/profiles/${activeProfileId}/diary/${entry.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ servings: Number(servings), meal_period: meal }) }); if (response.ok) await loadDay(activeProfileId, selectedDay); else setNotice('Could not update diary item') }
  async function copyEntry(entryId: string) { if (!activeProfileId) return; const target = window.prompt('Copy to date (YYYY-MM-DD)', addDays(selectedDay, 1)); if (!target) return; const response = await fetch(`${API}/profiles/${activeProfileId}/copy-entry`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entry_id: entryId, target_date: target, local_time: '12:00:00' }) }); setNotice(response.ok ? `Copied to ${target} as Planned` : 'Could not copy item') }
  async function copyMeal(section: MealPeriod) { if (!activeProfileId) return; const target = window.prompt('Copy this meal to date (YYYY-MM-DD)', addDays(selectedDay, 1)); if (!target) return; const response = await fetch(`${API}/profiles/${activeProfileId}/copy-meal`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_date: selectedDay, target_date: target, meal_period: section }) }); setNotice(response.ok ? `Meal copied to ${target} as Planned` : 'Could not copy meal') }
  async function copyDay() { if (!activeProfileId) return; const target = window.prompt('Copy this day to date (YYYY-MM-DD)', addDays(selectedDay, 1)); if (!target) return; const response = await fetch(`${API}/profiles/${activeProfileId}/copy-day`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_date: selectedDay, target_date: target }) }); setNotice(response.ok ? `Day copied to ${target} as Planned` : 'Could not copy day') }
  async function createProfile() { if (!profileDraft.display_name.trim()) { setNotice('Display name is required'); return } setSavingProfile(true); try { const mode = profileDraft.exercise_credit_mode; const percentage = mode === 'none' ? 0 : mode === 'full' ? 100 : Number(profileDraft.exercise_credit_percentage); const response = await fetch(`${API}/profiles`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: profileDraft.display_name.trim(), daily_calorie_target: Number(profileDraft.daily_calorie_target), weekly_exercise_minutes_target: Number(profileDraft.weekly_exercise_minutes_target), hydration_target_ml: profileDraft.hydration_target_ml === '' ? null : Number(profileDraft.hydration_target_ml), exercise_credit_mode: mode, exercise_credit_percentage: percentage, nutrition_display_mode: legacyMode(profileDraft.nutrition_display_fields), nutrition_display_fields: profileDraft.nutrition_display_fields, timezone: 'Australia/Melbourne', measurement_units: 'metric' }) }); if (!response.ok) throw new Error('Could not create profile'); const profile = (await response.json()) as Profile; setProfiles((current) => [...current, profile].sort((a, b) => a.display_name.localeCompare(b.display_name))); setActiveProfileId(profile.id); await fetch(`${API}/active-profile`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile_id: profile.id }) }); await loadDay(profile.id, selectedDay); setProfileDraft(emptyProfile); setView('today'); setNotice(`${profile.display_name} profile created`) } catch (err) { setNotice(err instanceof Error ? err.message : 'Could not create profile') } finally { setSavingProfile(false) } }
  async function saveProfilePreferences() { if (!activeProfile) return; const response = await fetch(`${API}/profiles/${activeProfile.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nutrition_display_fields: activeProfile.nutrition_display_fields, nutrition_display_mode: legacyMode(activeProfile.nutrition_display_fields), hydration_target_ml: activeProfile.hydration_target_ml }) }); if (response.ok) { const updated = (await response.json()) as Profile; setProfiles((current) => current.map((profile) => profile.id === updated.id ? updated : profile)); setNotice('Profile preferences saved') } }
  async function saveFood() { if (!foodDraft.name.trim() || !foodDraft.calories) { setNotice('Food name and calories are required'); return } setSavingFood(true); try { const numberOrNull = (value: string) => value === '' ? null : Number(value); const response = await fetch(`${API}/foods`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: foodDraft.name.trim(), brand: foodDraft.brand.trim() || null, kind: 'food', serving_name: foodDraft.serving_name.trim() || '1 serve', serving_grams: numberOrNull(foodDraft.serving_grams), calories: Number(foodDraft.calories), energy_kj: numberOrNull(foodDraft.energy_kj), protein_g: numberOrNull(foodDraft.protein_g), carbohydrates_g: numberOrNull(foodDraft.carbohydrates_g), fat_g: numberOrNull(foodDraft.fat_g), sugar_g: numberOrNull(foodDraft.sugar_g), favourite: false, notes: null, source: 'manual' }) }); if (!response.ok) throw new Error('Could not save food'); setFoodDraft(emptyFood); setNotice('Food saved and ready for Quick Add') } catch (err) { setNotice(err instanceof Error ? err.message : 'Could not save food') } finally { setSavingFood(false) } }

  if (loading) return <main className="state-page">Loading HealthHub…</main>
  if (error) return <main className="state-page"><h1>HealthHub</h1><p>{error}</p></main>

  const profileForm = <section className="profile-onboarding"><p className="eyebrow">Profile</p><h1>Create your first profile</h1><p>Profiles separate household nutrition records. They are data selectors, not secure accounts.</p><div className="food-form"><label>Display name<input autoFocus value={profileDraft.display_name} onChange={(e) => setProfileDraft({ ...profileDraft, display_name: e.target.value })} /></label><label>Daily calorie target<input inputMode="numeric" value={profileDraft.daily_calorie_target} onChange={(e) => setProfileDraft({ ...profileDraft, daily_calorie_target: e.target.value })} /></label><label>Weekly exercise target (minutes)<input inputMode="numeric" value={profileDraft.weekly_exercise_minutes_target} onChange={(e) => setProfileDraft({ ...profileDraft, weekly_exercise_minutes_target: e.target.value })} /></label><label>Hydration target (mL, optional)<input inputMode="numeric" value={profileDraft.hydration_target_ml} onChange={(e) => setProfileDraft({ ...profileDraft, hydration_target_ml: e.target.value })} /></label><label>Exercise calorie credit<select value={profileDraft.exercise_credit_mode} onChange={(e) => setProfileDraft({ ...profileDraft, exercise_credit_mode: e.target.value as ProfileDraft['exercise_credit_mode'] })}><option value="none">No exercise credit</option><option value="full">Full exercise credit</option><option value="percentage">Percentage exercise credit</option></select></label>{profileDraft.exercise_credit_mode === 'percentage' && <label>Exercise credit percentage<input inputMode="numeric" value={profileDraft.exercise_credit_percentage} onChange={(e) => setProfileDraft({ ...profileDraft, exercise_credit_percentage: e.target.value })} /></label>}<label>Nutrition display<NutritionMultiSelect value={profileDraft.nutrition_display_fields} onChange={(fields) => setProfileDraft({ ...profileDraft, nutrition_display_fields: fields })} /></label></div><button className="quick-add" disabled={savingProfile} onClick={() => void createProfile()}>{savingProfile ? 'Creating…' : 'Create profile'}</button></section>

  return <div className="app-shell"><header className="topbar"><div><div className="brand">HealthHub</div><div className="subtitle">Nutrition & activity</div></div><label className="profile-select"><span>Profile</span><select value={activeProfileId ?? ''} disabled={profiles.length === 0} onChange={(event) => void switchProfile(event.target.value)}><option value="" disabled>Select profile</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name}</option>)}</select></label></header>
    <main className="content">{notice && <div className="notice" role="status">{notice}</div>}{profiles.length === 0 ? (view === 'settings' ? profileForm : <section className="empty-card"><h1>Create your first profile</h1><button onClick={() => setView('settings')}>Open settings</button></section>)
      : view === 'today' ? <section><div className="page-heading diary-heading"><div><p className="eyebrow">Daily diary</p><h1>{displayDay(selectedDay)}</h1></div><div className="heading-actions"><button onClick={() => void copyDay()}>Copy day</button><button className="quick-add" onClick={() => setQuickAddOpen(true)}>+ Add Food</button></div></div><div className="date-nav"><button onClick={() => setSelectedDay(addDays(selectedDay, -1))}>Previous</button><input type="date" value={selectedDay} onChange={(e) => setSelectedDay(e.target.value)} /><button onClick={() => setSelectedDay(todayIso())}>Today</button><button onClick={() => setSelectedDay(addDays(selectedDay, 1))}>Next</button></div>{dayPlan && <><div className="target-grid"><article className="target-card"><span>Daily Goal</span><strong>{dayPlan.calorie_target.toLocaleString('en-AU')} kcal</strong></article><article className="target-card"><span>Eaten</span><strong>{dayPlan.consumed_calories.toLocaleString('en-AU')} kcal</strong></article><article className="target-card"><span>Planned</span><strong>{dayPlan.planned_calories.toLocaleString('en-AU')} kcal</strong></article><article className="target-card"><span>Remaining</span><strong>{dayPlan.remaining_after_planned.toLocaleString('en-AU')} kcal</strong><small>after planned food</small></article></div><div className="nutrition-strip"><article><span>Protein</span><strong>{dayPlan.protein_g} g</strong></article><article><span>Carbohydrates</span><strong>{dayPlan.carbohydrates_g} g</strong></article><article><span>Fat</span><strong>{dayPlan.fat_g} g</strong></article><article><span>Sugar</span><strong>{dayPlan.sugar_g} g</strong></article></div></>}
        <div className="meal-sections">{mealSections.map((section) => { const planned = (dayPlan?.planned ?? []).filter((entry) => normaliseMeal(entry.meal_period) === section.value); const consumed = (dayPlan?.consumed ?? []).filter((entry) => normaliseMeal(entry.meal_period) === section.value); return <section className="meal-section" key={section.value}><div className="section-heading"><h2>{section.label}</h2><div className="section-actions"><button onClick={() => void copyMeal(section.value)}>Copy</button><button onClick={() => { setMealPeriod(section.value); setQuickAddOpen(true) }}>+ Add</button></div></div>{planned.length === 0 && consumed.length === 0 ? <p className="muted compact-empty">Nothing added</p> : <>{planned.map((entry) => <article className="diary-row planned-entry" key={`p-${entry.id}`}><div><span className="meal-tag">Planned</span><strong>{entry.food_name}</strong><small>{entry.servings} × {entry.serving_name}</small></div><div className="diary-energy"><strong>{Math.round(entry.calories)} kcal</strong><div className="row-actions"><button onClick={() => void consumePlanned(entry)}>Mark eaten</button><button onClick={() => void editPlanned(entry)}>Edit</button><button onClick={() => void copyEntry(entry.id)}>Copy</button><button onClick={() => void deletePlanned(entry)}>Remove</button></div></div></article>)}{consumed.map((entry) => <article className="diary-row" key={`c-${entry.id}`}><div><span className="meal-tag eaten-tag">Eaten</span><strong>{entry.food_name}</strong><small>{entry.servings} × {entry.serving_name}</small></div><div className="diary-energy"><strong>{Math.round(entry.calories)} kcal</strong>{displayFields.includes('sugar') && entry.sugar_g != null && <small>{entry.sugar_g.toFixed(1)} g sugar</small>}<div className="row-actions"><button onClick={() => void editDiary(entry)}>Edit</button><button onClick={() => void copyEntry(entry.id)}>Copy</button><button onClick={() => void deleteDiary(entry)}>Remove</button></div></div></article>)}</>}</section> })}</div></section>
      : view === 'week' && activeProfileId ? <WeekView profileId={activeProfileId} onNotice={setNotice} />
      : view === 'progress' && activeProfileId ? <ProgressView profileId={activeProfileId} onNotice={setNotice} onActivityChanged={() => loadDay(activeProfileId, selectedDay)} />
      : view === 'food-import' ? <FoodImportView onNotice={setNotice} />
      : view === 'settings' ? <section><p className="eyebrow">Settings</p><h1>Foods & preferences</h1>{activeProfile && <section className="planner-card"><h2>{activeProfile.display_name} profile preferences</h2><label>Nutrition display<NutritionMultiSelect value={activeProfile.nutrition_display_fields} onChange={(fields) => setProfiles((current) => current.map((profile) => profile.id === activeProfile.id ? { ...profile, nutrition_display_fields: fields } : profile))} /></label><label>Hydration target (mL, optional)<input inputMode="numeric" value={activeProfile.hydration_target_ml ?? ''} onChange={(e) => setProfiles((current) => current.map((profile) => profile.id === activeProfile.id ? { ...profile, hydration_target_ml: e.target.value === '' ? null : Number(e.target.value) } : profile))} /></label><button className="quick-add" onClick={() => void saveProfilePreferences()}>Save profile preferences</button></section>}<div className="food-form"><label>Name<input value={foodDraft.name} onChange={(e) => setFoodDraft({ ...foodDraft, name: e.target.value })} /></label><label>Brand<input value={foodDraft.brand} onChange={(e) => setFoodDraft({ ...foodDraft, brand: e.target.value })} /></label><label>Serving<input value={foodDraft.serving_name} onChange={(e) => setFoodDraft({ ...foodDraft, serving_name: e.target.value })} /></label><label>Serving grams<input value={foodDraft.serving_grams} onChange={(e) => setFoodDraft({ ...foodDraft, serving_grams: e.target.value })} /></label><label>Energy (kJ)<input value={foodDraft.energy_kj} onChange={(e) => setFoodDraft({ ...foodDraft, energy_kj: e.target.value })} /></label><label>Calories<input value={foodDraft.calories} onChange={(e) => setFoodDraft({ ...foodDraft, calories: e.target.value })} /></label><label>Protein<input value={foodDraft.protein_g} onChange={(e) => setFoodDraft({ ...foodDraft, protein_g: e.target.value })} /></label><label>Carbs<input value={foodDraft.carbohydrates_g} onChange={(e) => setFoodDraft({ ...foodDraft, carbohydrates_g: e.target.value })} /></label><label>Fat<input value={foodDraft.fat_g} onChange={(e) => setFoodDraft({ ...foodDraft, fat_g: e.target.value })} /></label><label>Sugar<input value={foodDraft.sugar_g} onChange={(e) => setFoodDraft({ ...foodDraft, sugar_g: e.target.value })} /></label></div><button className="quick-add" disabled={savingFood} onClick={() => void saveFood()}>{savingFood ? 'Saving…' : 'Save food'}</button></section>
      : <section className="empty-card"><h1>Select a profile</h1></section>}</main>
    <nav className="bottom-nav" aria-label="Primary navigation"><button onClick={() => setView('today')} aria-current={view === 'today' ? 'page' : undefined}>Today</button><button disabled={profiles.length === 0} onClick={() => setView('week')} aria-current={view === 'week' ? 'page' : undefined}>Week</button><button disabled={profiles.length === 0} onClick={() => setView('progress')} aria-current={view === 'progress' ? 'page' : undefined}>Progress</button><button onClick={() => setView('settings')} aria-current={view === 'settings' ? 'page' : undefined}>Settings</button><button onClick={() => setView('food-import')} aria-current={view === 'food-import' ? 'page' : undefined}>Import</button></nav>
    {quickAddOpen && <div className="sheet-backdrop" onClick={() => setQuickAddOpen(false)}><section className="quick-sheet" onClick={(event) => event.stopPropagation()}><div className="sheet-handle" /><h2>Add Food</h2><div className="quick-mode"><button className={quickAddMode === 'eaten' ? 'active' : ''} onClick={() => setQuickAddMode('eaten')}>Eaten</button><button className={quickAddMode === 'planned' ? 'active' : ''} onClick={() => setQuickAddMode('planned')}>Planned</button></div><label className="meal-period">Meal<select value={mealPeriod} onChange={(e) => setMealPeriod(e.target.value as MealPeriod)}>{mealSections.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="meal-period">Servings<input inputMode="decimal" value={quickServings} onChange={(e) => setQuickServings(e.target.value)} /></label><div className="capture-entry-points"><button className="quick-add" onClick={() => setCaptureOpen(false)}>Search</button><button onClick={() => { setQuickAddOpen(false); setView('food-import') }}>Scan Barcode</button><button onClick={() => setCaptureOpen(true)}>Take Photo</button><button onClick={() => setCaptureOpen(true)}>Upload Photo(s)</button></div>{captureOpen && activeProfileId ? <CaptureFoodSheet profileId={activeProfileId} day={selectedDay} mealPeriod={mealPeriod} mode={quickAddMode} servings={Number(quickServings) || 1} onClose={() => { setCaptureOpen(false); setQuickAddOpen(false) }} onSaved={() => loadDay(activeProfileId, selectedDay)} onNotice={setNotice} /> : <><input autoFocus aria-label="Search foods and meals" placeholder="Search favourites, recent foods or recipes" value={search} onChange={(e) => setSearch(e.target.value)} />{searching && <p className="muted">Checking FoodHub… local results stay available.</p>}<div className="search-results">{searchResults.map((result) => <button disabled={savingEntry} key={`${result.source}-${result.id}`} className="search-result" onClick={() => void addSearchResult(result)}><span><strong>{result.name}</strong><small>{result.subtitle} · {result.source === 'foodhub' ? 'FoodHub Recipe' : 'HealthHub'}</small></span><b>{result.calories == null ? 'Nutrition pending' : `${Math.round(result.calories)} kcal`}</b></button>)}</div></>}<button onClick={() => { setCaptureOpen(false); setQuickAddOpen(false) }}>Close</button></section></div>}
  </div>
}
